### ISSUE TITLE
Deregistered Account with App Update

### ISSUE THREAD

**Issue by arthurghwindsor** [johanw666/Signal-Android#100]
Whenever updates are made by installing on top of a previous version it "de-registers" the account from Signal's servers. The person with the JW app after update can still send messages like normal and the receiver can still receive the messages however the chat window would say the number is not registered with signal. Attached is a screenshot of the error on my fiance's phone using Molly when chatting with me (I use the JW version)
![Screenshot_20240511-125757~2](https://github.com/johanw666/Signal-Android/assets/169523855/ec1bf43e-07cf-4bde-930d-339512903a8f)

**Comment by johanw666** [comment]
Odd. I had issues with registrations years ago but those were solved years ago and were not related to updates. Can you send a debug log?

**Comment by arthurghwindsor** [comment]
After updating I cleared the App storage to reactivate my account so I've successfully recreated the error by downloading the previous version (7.7.0.0-JW) and updating it to the latest version (7.7.1.0-JW) and I'm sending the debug files for both versions (named accordingly). Btw this has been happening for some time now and I just thought Signal was trying to block access from forks so I didn't think much of it until I noticed the pattern after every update.
[(7.7.0.0-JW)signal-log-1715527929075.zip](https://github.com/johanw666/Signal-Android/files/15286906/7.7.0.0-JW.signal-log-1715527929075.zip)
[(7.7.1.0-JW)signal-log-1715529390867.zip](https://github.com/johanw666/Signal-Android/files/15286907/7.7.1.0-JW.signal-log-1715529390867.zip)

**Comment by arthurghwindsor** [comment]
Thanks it solved the issue, also using Google FCM on GrapheneOS barely manages to deliver notifications on time anyway so...
