### ISSUE TITLE
Issues registering with a Nigeria IP address or mobile number

### ISSUE THREAD

**Issue by Abeefe** [johanw666/Signal-Android#102]
- [ x] I have searched open and closed issues for duplicates
- [ x] I am submitting a bug report for existing functionality that does not work as intended
- [ x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
I can't register on Signal with a Nigerian mobile number which starts with +234.
I use Signal only and lately it has been having people in my country Nigeria to resgister on Signal, it's like Signal server is either blocking Nigeria IP addresses or mobile number even with a VPN. 

### Steps to reproduce
- Download Signal from Play Store or official website 
- grant all permissions requested when initializing registration
- try to register with a Nigeria mobile number or IP address
- Get stuck in endless captcha or whatever.

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)

### Device info

**Device:** Pixel 5a
**Android version:** 13.0.0
**Signal version:** 7.8.1

**Comment by johanw666** [comment]
This has nothig to do with my fork, I suggest you report it to the original Signal repo.
