### ISSUE TITLE
Unable to register with FCM due to mismatch API Keys

### ISSUE THREAD

**Issue by jackfagner** [johanw666/Signal-Android#104]
- [X] I have searched open and closed issues for duplicates
- [X] I am submitting a bug report for existing functionality that does not work as intended
- [X] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [X] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Signal-JW is currently unable to register with Firebase Cloud Messaging (FCM) due to upstream API keys being restricted by APK signature. Signal is pinning their FCM keys to their APK signing keys. You need to change the FCM keys in firebase_messaging.xml when compiling (signing) a Signal fork.
- This as actually a (slightly better described) duplicate of issue https://github.com/johanw666/Signal-Android/issues/99
- This issue is most likely the root cause for issue https://github.com/johanw666/Signal-Android/issues/100
- Here is the description from Signal: https://github.com/signalapp/Signal-Android/issues/13451
- Here is the issue and the commit for solving this issue in Molly:  https://github.com/mollyim/mollyim-android/issues/291 https://github.com/mollyim/mollyim-android/commit/e49c29fb4e75c9e3bf4e6a2387b426d99770cec8

### Steps to reproduce
- Install Signal-JW
- Register account
- Enable notifications using FCM

**Actual result:** Notifications are delayed until you open the app. FCM will log "FIS_AUTH_ERROR"
**Expected result:** Instant notifications on new messages

### Device info
**Device:** Asus Zenfone 8
**Android version:** 13
**Signal version:** 7.9.6

**Comment by johanw666** [comment]
I have issues on one device, it works on another but if this is the issue, can you please tell me which keys to put there? Should I just generate keys?

**Comment by jackfagner** [comment]
According to the Signal issue https://github.com/signalapp/Signal-Android/issues/13451 _"you must register your own Firebase API tokens paired to your signing key"_. 
Also note, not all of the values should be changed, only these four:
- google_app_id
- google_api_key
- google_crash_reporting_api_key
- project_id

I haven't generated Firebase keys myself, so I'm not 100% sure how it's done, but I assume you login with your developer account and generate new keys. These instructions might help: https://firebase.google.com/docs/projects/api-keys

**Comment by johanw666** [comment]
I found a solution on https://github.com/signalapp/Signal-Android/issues/13451#issuecomment-1978237171

Starting to upload a new build now, please let me know if this fixes it.

**Comment by jackfagner** [comment]
The keys seem to be changed in the APK, but still no working FCM registration. 
Here are some relevant lines from the debug log: [fcm_log.txt](https://github.com/user-attachments/files/15979335/fcm_log.txt)

**Comment by johanw666** [comment]
Ah I forgot to change the project_id. It should work in 7.10.1.0-JW

**Comment by jackfagner** [comment]
Sorry to say, it's still not working :-/
Same error in the log file:
`06-27 09:01:14.407  6320  6341 E FirebaseMessaging: Failed to get FIS auth token`
`06-27 09:01:14.407  6320  6341 E FirebaseMessaging: java.util.concurrent.ExecutionException: com.google.firebase.installations.FirebaseInstallationsException: Firebase Installations Service is unavailable. Please try again later.`
and
`06-27 09:01:15.150  6320  6373 W FcmUtil : Failed to get the token.`
`06-27 09:01:15.150  6320  6373 W FcmUtil : java.io.IOException: java.util.concurrent.ExecutionException: java.io.IOException: FIS_AUTH_ERROR`

**Comment by johanw666** [comment]
Strange, I didn't see the error in my logs anymore since 7.10.0.2-JW (a test version with the fix I never released). I have not seen it with 7.10.1.0-JW either.

**Comment by jackfagner** [comment]
It must have been some mistake on my end. I did a fresh test just now with 7.10.1.0 and FCM seem to be working. Great job! You may close this issue.
