### ISSUE TITLE
Allow Native Android Backup

### ISSUE THREAD

**Issue by mentalisttraceur** [johanw666/Signal-Android#11]
Can you please delete [the line that disables Android backups](https://github.com/johanw666/Signal-Android/blob/a5a6fb590a9799e6ebb24e7303c755d6209c04d8/app/src/main/AndroidManifest.xml#L98), or change it to true?

This would allow people to use `adb backup` to get the entire app data.

Of course, the caveat is that if you enable this, the app data becomes eligible for Google Cloud backups, with whatever potential security risks of leaking private Signal data to/through Google servers that entails.

**Comment by johanw666** [comment]
A backup made this way would be useless (except on Android 4 and 5 devices). On Android 6 and above, the Signal database is encrypted with a key stored in the Android keystore that can not be copied this way, so after restore Signal would crash on an unreadable database.

The custom "Encrypted backup" option from the main menu stores these files, AND a copy of the required keys that allow it to restore them on another device.

**Comment by mentalisttraceur** [comment]
Oh, that's good to know! Thanks!
