### ISSUE TITLE
Add an attribute to plain text backup indicating signal vs sms message

### ISSUE THREAD

**Issue by Kingwad** [johanw666/Signal-Android#13]
SMSBackupAndRestore will ignore unknown attributes in sms elements when restoring backups (I tested to confirm). Would it be possible to add an attribute to the backup indicating whether a message was an unsecured sms or a signal message? The app database knows this (shows unlocked icon on sms messages).

The use case here is to migrate away from using Signal as the system sms app, and to copy the sms conversation history out of Signal and into the system database.

One could export messages from signal, edit the xml to remove signal messages, and then import only sms messages into Android's stock sms database.

**Comment by johanw666** [comment]
I am working on the plaintext export now to add other things (and fix a crash when the sender is null), I could add this too.

**Comment by johanw666** [comment]
I just published 4.75.1.1-JW with an extra column "transport" in the plaintext backup export. It can get the values "-" (failed to send), "Pending", "Data", "SMS" and "MMS".
