### ISSUE TITLE
Design bright with green is missing in latest version 

### ISSUE THREAD

**Issue by Wolle980** [johanw666/Signal-Android#15]
- [ ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behaviour)
**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behaviour)

### Device info

**Device:** Manufacturer Model XVI
**Android version:** 0.0.0
**Signal version:** 0.0.0

**Comment by Wolle980** [comment]
![_20201124_154852](https://user-images.githubusercontent.com/42203108/100110146-e9df4000-2e6c-11eb-81c4-d06204699f83.JPG)

**Comment by Wolle980** [comment]
I'm missing bright green design. Maybe also a bright blue design was available in former releases

**Comment by johanw666** [comment]
Yes, I'm sorry I had to remove those but after the latest total refactoring of the design in 4.78 I didn't manage to get those working correctly in a reasonable time.

**Comment by Wolle980** [comment]
Thank you for your quick reply!
Can you please predict, when these designs will be available again?

**Comment by johanw666** [comment]
The highest priority now is get the backupsworking with Android 10 / 11. After that I can spend some time on that.
