### ISSUE TITLE
Share menu doesn't show signal contacts?

### ISSUE THREAD

**Issue by aouni84** [johanw666/Signal-Android#17]
I noticed that the share menu on my samsung phone doesn't show signal contacts to directly share a link or photo from another app to a signal contact?

It was available when I used the official app. 
Is this something related to jw version or am I missing something?

Note: Quick share is enabled in the android settings.
Thanks

**Comment by johanw666** [comment]
Sorry, Ihave no idea what exactly you mean. Which menu from which app doesn'tshow which contacts?

**Comment by aouni84** [comment]
I attached an illustration and circled it in red. Inside the share menu, there's a quick share option that shows contacts from my phonebook. For instance, in the screenshot, it shows an option to directly share the image with a specific contact through Google Messages app. Hope that's clear. 

[20210124_200956](https://user-images.githubusercontent.com/35864878/105650015-4b795600-5e80-11eb-859d-4fe6eaf12c32.jpg)

**Comment by aouni84** [comment]
It's working now.
