### ISSUE TITLE
Newbie Guide to Install

### ISSUE THREAD

**Issue by o-data** [johanw666/Signal-Android#18]
Just recently found out about this build and some of the feature is interesting. Would like to install it but I can't install it due to already having a Signal installation (Google Play Store version).

What is the best approach to install this build? 

Some of the way I can think of is as follow but I'm not sure which is the best way to do this.
Uninstall the current app and install johanw666 version, would this delete existing data (conversation, group, contact, media, etc)?

Do a backup, uninstall and install?

Create a PIN, uninstall and install?

**Comment by johanw666** [comment]
If you uninstall your current version you lose all conversations so making a backup first is advisable. Then you can uninstall, inslall my fork and restore your backup.

If you have a rooted device there are other options though with xposed modules or Lucky Patcher to disable apk signature checking.

**Comment by o-data** [comment]
Thank johanw, the disable signature checking method work.

**Comment by o-data** [comment]
Considered this solve. Future user can rely on it to make installation.
