### ISSUE TITLE
Exporting Plaintext SMS "Error, unable to write to storage.

### ISSUE THREAD

**Issue by xNyxNox** [johanw666/Signal-Android#19]
Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.
When click the "Export plaintext backup" button, an error message appears saying "Error, unable to write to storage."  I believe that this is due to the app only requesting media access in Android 11 instead of access to all storage.

After asking for help on reddit, someone offered their advice on how this could be handled and asked me to include his comments in this request.  I'm editing this to include them.  [Here is the link](https://www.reddit.com/r/AndroidQuestions/comments/l5psr3/how_to_manually_add_permissions_in_android_11/gkw4fzt?utm_source=share&utm_medium=web2x&context=3)

### Steps to reproduce
- Tap 3 dots in top right
- Tap "Import / export"
- Tap "Export plaintext backup"

**Actual result:** "Error, unable to write to storage." appears on the bottom of the screen.
**Expected result:** A backup should begin to be created.

### Screenshots

https://imgur.com/a/xis6qPV 
https://imgur.com/a/0tVo8oF 

### Device info

**Device:** Samsung Galaxy S10
**Android version:** 11
**Signal version:** 5.3.6.0-JW

### Link to debug log

https://debuglogs.org/1e03c87453b7fd4a6f68bb5cf518e1150c8162d59c034cec706a96f41dd9d585

**Comment by johanw666** [comment]
I see a NoExternalStorageException.  If you go to Settings - Chats - Chat Backups, what is written below the backup folder section?

And do you have a micro sd card installed in the device?

**Comment by xNyxNox** [comment]
> I see a NoExternalStorageException. If you go to Settings - Chats - Chat Backups, what is written below the backup folder section?
> 
> And do you have a micro sd card installed in the device?
> 
> Yu could try making a standard backup in the same directory you want to export the plaintext to (or one lower in the same path) and see if it works afterward.

Here is a screenshot of the path you asked me to go to.  I don't see a "backup folder" option, not sure if it's related.
https://imgur.com/a/ZS65gCq
Also there is a screenshot of what happens when I try to make a backup using the "Create backup" option.  That notification pops up for around 5 seconds, then disappears and as far as I can tell from making backups in the normal Signal app, it isn't making a backup.  I also tried exporting an encrypted backup (through similar means that I tried exporting the plaintext backup) and got the original error.

**Comment by xNyxNox** [comment]
I've updated to the most recent build (5.2.11.0-JW) from 8 hours ago and the problem persists.

You asked about external storage, do I need a microSD card in my phone in order to perform a backup?  

Additionally, since it seems like standard backups also don't work as far as I can tell simply uninstalling the fork and trying something else isn't really an option since I'd lose all messages.

I realize this is likely something that you build and maintain out of your interest and because you personally see the benefit of having these features.  Personally, I have a lot of SMS messages stuck in Signal that I would really love to get out and honestly I don't know of a way to do it other than this incredible fork.  If there is a Ko-fi or something that you have I'd be happy to donate for your time.  If there is any more information or help you can provide about how I may be able to get this to work, that would be amazing.

**Comment by johanw666** [comment]
You have not made a "normal" backup at all, then this probably does not work at the moment. I intend to make changes for Android 11 to fix this once and for all but I have to wait for my device to get Android 11 to develop and test this.

**Comment by xNyxNox** [comment]
Seems to have been solved in recent updates! :)
