### ISSUE TITLE
"Added more themes" no longer available

### ISSUE THREAD

**Issue by o-data** [johanw666/Signal-Android#20]
Might be because I install using Signature verification disable.

Let's begin with a checklist: Replace the empty checkboxes [ ] below with checked ones [x] accordingly. -->

- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
On the website it say that there is more addition theme https://johanw.home.xs4all.nl/Signal/signal-jw.html

### Steps to reproduce
- Using version  5.3.10.0-JW Signal-Android-play-prod-universal-release-5.3.10.0-JW.apk
- Install and open App
- Setting > Appearance > Theme > only Light and Dark available

**Actual result:** only Light and Dark available, missing the other 3 options as per screenshot in website
**Expected result:** 3 extra theme option available.

### Device info
**Device:** 
**Android version:** 
**Signal version:** 5.3.10.0

**Comment by johanw666** [comment]
This became too difficult to maintain due to frequent changes in the UI so unfortunately I had to remove it. I will adapt the website.

**Comment by o-data** [comment]
All good in that case.
