### ISSUE TITLE
Doesn't work on A11

### ISSUE THREAD

**Issue by ProblematicDude** [johanw666/Signal-Android#23]
- [✓ ] I have searched open and closed issues for duplicates
- [ ✓] I am submitting a bug report for existing functionality that does not work as intended
- [✓ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ✓] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App doesn't work on Android 11 in sense that If i grant storage permission then backup option doesn't work and if revoke that storage permission then I can't share media. 

I know this is strange. I can record and share the video if you ask. But backup option and storage access can't co exist.

And strangely signal can write the storage without write storage access. *\0/*

I have tested , things are OK in offical app

### Steps to reproduce
- Grant storage access from the signal dialogue.
- Go to backup section.
- Backup won't work.
- Media sharing in chat works

Or
- revoke storage access. 
- go to backup section.
- it'll work fine. 
-go to any chat. Try to send any media. Yoy can't as we revoked the permission in first step.
- if you grant that permission , then backup won't work.

**Actual result:** 
We can either enable backup or give storage access to share media (photos/files)

**Expected result:** 
- Backup and storage access should exist.

### Screenshots

**Revoked storage access permission**

![Revoked storage access ](https://user-images.githubusercontent.com/59223300/108461966-c4ae7200-72a1-11eb-9bfd-43d913c169ce.png)

![Backup working fine](https://user-images.githubusercontent.com/59223300/108462025-e3146d80-72a1-11eb-9bf6-6e583b172859.png)

Strange that with revoked storage permission. Signal can write the storage.
*\0/*
 

**Signal ask for storage access**

![Singal asks for permission to access](https://user-images.githubusercontent.com/59223300/108462048-ef98c600-72a1-11eb-9c24-cbf2907ddd3d.png)

**And now if i grant that**

![Granted access](https://user-images.githubusercontent.com/59223300/108462112-06d7b380-72a2-11eb-882f-c1d3356c83ff.png)

**Media access working fine**

![Access granted so it works fine](https://user-images.githubusercontent.com/59223300/108462126-122adf00-72a2-11eb-869c-947b5cb3070d.png)

**Backup doesn't work anymore**

![Backup doesn't work anymore](https://user-images.githubusercontent.com/59223300/108462164-2a026300-72a2-11eb-90a8-bf98dc59a2d2.png)

### Device info

**Device:** Redmi note 7 pro.
**Android version:** 11
**Signal version:** 5.4.6 jw

###Debug log

With storage access granted

https://debuglogs.org/5c29492479e307d735af8d9c0d9e1e81f6007ccfb25c57a71b4d63f4acdd6d60

With Revoked access

https://debuglogs.org/8136dd917bf032bc48a99b0ed2a091340f6789927a464a956bd14597e6aae872

**Comment by CSab6482** [comment]
I'm also having problems on Android 11

**Comment by Ahsan40** [comment]
I have faced the same issue yesterday. I fixed it by giving it enabling full file access. Initially the permission this all gets is ***only media**. All you have to do to fix it is, give the app full permission. Check the screenshot below,

![Screenshot_20210503-134005781](https://user-images.githubusercontent.com/30434801/116851878-19148d00-ac15-11eb-8782-f6eb2dd2931e.jpg)
