### ISSUE TITLE
Sms backup doesn't work

### ISSUE THREAD

**Issue by Bazarov42** [johanw666/Signal-Android#24]
Hi,

When i want export plaintext backup i have an error "error, unable writee to storage", same for import encrypted backup.
I have a Oneplus 8 Pro Android 11

**Comment by johanw666** [comment]
You need to make a "standard" backup first in the desired location on the removable or internal storage before the directory becomes writable. On Android 10 this is unavoidable, when I finally get Android 11 on my device I can test with adding the required permission (manage storage permission) to fix this proper.

**Comment by Bazarov42** [comment]
Thanks for the quick reply, i can't make a "standard" backup, or anything, i have the same error.
I want make an encrypted backup i have the error, same for plaintext backup.
I want import a backup, i have the error too.

Or maybe i don't understand what is a "standard" backup ^^

**Comment by johanw666** [comment]
That is the backup that the official Signal client offers, menu - settings- chats - chat backups - create backup.

**Comment by Bazarov42** [comment]
ok, i tried it, same problem, the "official" backup works but when i want make a plaintext backup it say "error, unable write to storage"

**Comment by ProblematicDude** [comment]
> ok, i tried it, same problem, the "official" backup works but when i want make a plaintext backup it say "error, unable write to storage"

I guess we got same issue.  It doesn't seem to be working on Android 11.

**Comment by Bazarov42** [comment]
Ok, thanks for your answer,
I just want to have my messages unencrypted, if there are other techniques, I take.

**Comment by Bazarov42** [comment]
To keep you informed
Same problem with 5.5.1.0-JW version.

**Comment by johanw666** [comment]
I implemented a fix for Android 11 in 5.5.2.0-JW but I can't test it, could you please try? The first time you try to export or import a backup you should get a system popup asking permission to manage the file system.

**Comment by Bazarov42** [comment]
I succed to import the sms from the encrypted backup when installing the application, but unable to make a plaintext backup
I have record the problem

https://www.youtube.com/watch?v=h5T7ty5Aqgo

**Comment by Bazarov42** [comment]
It works !
![InkedScreenshot_20210319-134840_LI](https://user-images.githubusercontent.com/77288094/111783252-5073e800-88ba-11eb-809b-922abad41666.jpg)
you must choose "authorize the management of all files"

thks Johanw for your app !

**Comment by Go-rom** [comment]
Thank you @Bazarov42 for this tip, it just helped me 👍
