### ISSUE TITLE
Add new update notification system

### ISSUE THREAD

**Issue by Ahsan40** [johanw666/Signal-Android#29]
I am really sorry because it's not a bug, it's a feature request. But please at least read the request, I promise it's related to this forked version.

Ok. So, the feature I am requesting is new update notification. Since this is a forked version we won't get updates fron app store. So, it would be really nice to have a new update notification system.

**Comment by johanw666** [comment]
I have some ideas about that: set an exclamation mark as reaction with yourself as sender. Unfortunately but I'm currently quite busy so I have to prioritize.

**Comment by johanw666** [comment]
You can star this repository and set notifications on release only, that should work. Further, since Signal's package name is not changed, the Play Store will notice if there are updates of the official version (but can't install them due to signature mismatch).
