### ISSUE TITLE
Can't export messages

### ISSUE THREAD

**Issue by Ulikuo** [johanw666/Signal-Android#33]
Choosing export leads to the app crashing.

**Comment by Centazi** [comment]
I was having the same problem. Solved it by manually giving storage permission to the app. The correct behavior should be to have a prompt asking for the permissions but for some reason it doesn't.

**Comment by johanw666** [comment]
I finally got a stable Android 11 device to test with and most export issues are fixed in 5.23.1. The system prompt asking for all file access works now. On Android 11 the export directory can be anywhere, not only in Signals own directory in internal or external storage.

**Comment by Go-rom** [comment]
Hello @johanw666 

just a quick question : there was a time where backupping to external storage was not safe.
Problem was : backups were deleted when uninstalling Signal.

Is this still true ? (I'm running Android 12 btw)

**Comment by johanw666** [comment]
This issue is only the case with Android 10 and lower. On Android 11 and up you can select almost any location for the backup files.

On the official Signal this can be done from Android 10 and up, but due to some limitations for the other backups I was not able to implement that on Android 10.

**Comment by Go-rom** [comment]
Great, thanks a lot :+1:
