### ISSUE TITLE
Feature request: Add a toggle for the old UI

### ISSUE THREAD

**Issue by Redn2000** [johanw666/Signal-Android#34]
After updating, I saw that the new UI for contacts on the left-hand side looks awful, and there isn't a way to go back without staying on an old install. Would it be possible to add a toggle to go back to the old UI for contacts?

**Comment by johanw666** [comment]
Technically that would be possibe but it would require so much work and especially maintenance that I don't have the time for it.

**Comment by Redn2000** [comment]
> Technically that would be possibe but it would require so much work and especially maintenance that I don't have the time for it.

That's unfortunate, but understandable. I hope the official Signal team finally realizes how ugly the new UI is and allows users to add the old style back through a toggle or the like.
