### ISSUE TITLE
App Craches on Launch

### ISSUE THREAD

**Issue by UmbraChimera** [johanw666/Signal-Android#35]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
App crashes as soon I get past the step to select a PIN

### Steps to reproduce
- Setup new account and follow the steps

**Actual result:** App crashes to the Android not responding pop-up
**Expected result:** App to continue

### Device info

**Device:** Moto x4
**Android version:** 9
**Signal version:** 5.23.1.1JW

**Comment by johanw666** [comment]
Without a debug log I can't do anything with this. If Signal keeps crashing you can try adb or (on a rooted device) an Android app that reads logs.
