### ISSUE TITLE
feature request: link timeout, chat history synching or chat history export for desktop client

### ISSUE THREAD

**Issue by themaikmueller** [johanw666/Signal-Android#39]
So, I finally stumbled across a scenario where I lost a link to a Windows desktop. Might have been that time-limit, but I thought I was at 29 days.

And since Signal doesn't sync histories when relinking, I have a messed-up chat history with gaps on my new desktop. This isn't really ideal.

So there came up a few questions/thoughts: 
Could this behavior be easily changed? Like making the "not synching chat histories for security reasons" an optional thing?
Could the Android-Client's export function produce a file-set that can be imported into a windows desktop client?
Could that 30day time-out be turned off, or main-client enhanced to spit out warnings?

I basically haven't found a work-around, or modded Windows client, that comes with enhanced import/export functions like your Android mod.

BTW, great work here!

Best regards.

**Comment by johanw666** [comment]
No, that is quite complicated. Messages are sent separately to all connected clients, there is no central repository like Telegram's where all messages are stored. The 30 day limit is enforced by the server so I have no influence on that.

The only option I see is using an xml export from my fork, and importing a manually selected part of that in de desktop client. However, changing the desktop client for that purpose, or writing a separate xml imported for the desktop[ database is non trivial and currently outside my planning.

**Comment by themaikmueller** [comment]
Yes, I completely understand. Kinda how I assumed things, so it's good to get confirmation from someone who knows the source-code. Thank you very much.
