### ISSUE TITLE
Unable to install on Samsung Galaxy S7

### ISSUE THREAD

**Issue by km22** [johanw666/Signal-Android#4]
- [x ] I have searched open and closed issues for duplicates
- [ ] I am submitting a bug report for existing functionality that does not work as intended
- [ ] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [ ] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Whenever I try to install the johanw666/Signal-Android on my Samsung S7 the installation fails

### Steps to reproduce
- download either apk provided on this github project
- follow install steps on my Samsung S7
- note: I did not delete the existing version of the official Signal app from the Play Store

**Actual result:** Installation fails
**Expected result:** Expect the installation to complete and to utilize existing database/data

### Device info

**Device:** Samsung S7 SM-G930FD
**Android version:** 8.0.0
**Signal version:** 4.49.18

**Comment by johanw666** [comment]
That is to be expected. My version is signed with a different signing key that the official version (as I obviously do not have access to the OWS signing key), and standard Android checks if the signature of a new version matches the signature of an already installed version. If they don't match installation is aborted.

There are 2 solutions:

1. Make a backup, uninstall, install my version and restore the backup.
2. Root your device (if you didn't do it already) and install software that can disable this signature checking machanism. On Android 8 I believe that the Xposed module XInstaller doesn't work any more, but  [Lucky Patcher](https://www.luckypatchers.com/) has an option to disable that: Toolbox - Patch to Android - Disable signature verification in the package manager.

**Comment by km22** [comment]
Thanks.  And which of the 2 apk's should I use on my device? (What is the difference?)

**Comment by johanw666** [comment]
The difference is the processor architecture that is supported: the armv7a has only an arm 32 bit libraries and will work on most devices (except the rare x86 based ones), the universal apk has support for arm and x86 32 and 64 bit and might work faster on 64 bit architectures but is therefore larger. For your device both versions will work, but since I can't quickly find if you have 64 bit support I don't know if you might gain anything by using the universal apk.

**Comment by km22** [comment]
Works great! Thank you
