### ISSUE TITLE
[Feature Request specific to this Signal-JW]

### ISSUE THREAD

**Issue by pixincreate** [johanw666/Signal-Android#43]
A feature-request that is related to WhatsApp and Signal App **bridging**.   
Everything is detailed in points from below.
- I got inspired from [this¹](https://github.com/meinto/whatsapp-signal-bridge) and [this²](https://github.com/adeekshith/watomatic).      
- We all know that WhatsApp(WhatsCrap) is closed source and doesn't allow bridging easily.
- However, it does allow notifications that can be read without opening.
- So, my thought is that every time you receive a message on WhatsApp, either read it from notification or add a compatibility with ¹(mentioned above).
- Open a new chat with Name "WhatsApp received"  or whatever but it has to start with the word "WhatsApp" for better identification along with its logo, and throw the message over there in the way that is mentioned in ¹ and upon quoting reply, it has to send reply to that specific chat.
- If sending messages through notification panel, the app will have to be given the access to **Notification Access** in the device settings. 
- And another thing is that, adding in-app update to update this app without visiting the website everytime to check for update.

**Comment by johanw666** [comment]
Sorry but writing a bridge like that is out of scope of this project. It would not protect your messages in transit any better because WA would have the metadata already.

About the updates, since you have a Github account you can watch this project and send notifications when there is a new release. It will then send an email to you.

**Comment by pixincreate** [comment]
That's sad. But ok, I can agree with the first part. However, regarding the in-app updates, you can implement it directly from Molly.im which is also a hardened version fork of Signal itself.



Is it possible to add the proper read receipts? What I meant to say is that, Signal as of now IMO has the worst info page. Meaning, you get the deliver message, but when read, it doesn't show the time of reading the message. Instead we get to see the stuff that has to be for group chats.  
Example:
```
deliver time: 16:49:24
read time: 18:01:55
```
Instead of traditional
```
Delivered to: 06:37:24
```
Upon reading,
```
Read by
<contact_name><white tick>
```
