### ISSUE TITLE
Multi Device

### ISSUE THREAD

**Issue by xyz-nobody** [johanw666/Signal-Android#51]
Could you integrate an old fork so that Signal is Multi Device?

https://github.com/andrewmattie/Signal-Android-Multidevice

**Comment by johanw666** [comment]
It is a fork of a fork I know off, and while I like the functionality (I'm waiting for it to run it on my own tablet) it has so many changes that also need updating to the latest Signal code that maintaining it will cost kore time than I have available. So I'm waiting for Signal to implement something like this themselves.
