### ISSUE TITLE
Add features from molly.im

### ISSUE THREAD

**Issue by xyz-nobody** [johanw666/Signal-Android#52]
nice what you added, but you should look at the work of Molly.im which added a lot of functionality in addition, (call that erases etc etc), why not work from the fork of molly to improve your side?

**Comment by johanw666** [comment]
As long as Molly does not receive notifications when its database is locked it is not usable for me as a daily driver. Further I want to keep the changes to the original Signal code limited to reduce maintenance time. Maintaining Molly against new Signal updates is a lot more work for which I have no time available now.
