### ISSUE TITLE
Unable to restore account/chats..App force closed

### ISSUE THREAD

**Issue by aravind-alpha07** [johanw666/Signal-Android#53]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description
Unable to restore my chat backup.. App Crashes and Force Closed when I gave contacts permission in "Transfer account" during setup

### Steps to reproduce
- When clicking on "Restore Account" app force closed after I gave contact permission during setup

**Actual result:** App force closed after I gave contact permission for the app during setup I can't able to restore my chat/account
**Expected result:**Should not be force closed 

### Screenshots
  Screenshots I attached below 
![Screenshot_2022-04-30-12-45-31-355_org.thoughtcrime.securesms.jpg](https://user-images.githubusercontent.com/93417425/166096173-71025244-cfd9-4b53-86df-c7e3b7c1faf1.jpg)

![Screenshot_2022-04-30-12-45-40-210_com.miui.home.jpg](https://user-images.githubusercontent.com/93417425/166096187-def2a120-51ec-4bfc-990c-475fda748d2d.jpg)

### Device info

**Device:** Xiaomi Redmi Note 10 Pro (Miui 13)
**Android version:** 12.0
**Signal version:** 5.36.3.0-JW

**Comment by johanw666** [comment]
Did you try to restore from a backup file or a transfer? Or did it crach before you got to maake this choice? If it was a backup, which version was it made with? And do you have a debug log?

**Comment by aravind-alpha07** [comment]
> Did you try to restore from a backup file or a transfer? Or did it crach before you got to maake this choice? If it was a backup, which version was it made with? And do you have a debug log?

Now I solved it bro..

I tried with AOSP Roms it worked perfectly after I got help from reddit community that the latest Miui system update for my device blocks device info permission by default returning blanking messages then by giving permission to allow It worked 

![Screenshot_2022-05-02-09-12-53-515_com.miui.securitycenter.jpg](https://user-images.githubusercontent.com/93417425/166181895-a352ebcc-f941-49b4-a382-7d3d89396828.jpg)


Sorry for wasting your time it's my bad 
Now it works perfectly 

Thank you
