### ISSUE TITLE
Plaintext export of groupchat isn't working properly

### ISSUE THREAD

**Issue by v3ctr0n** [johanw666/Signal-Android#57]
Export of groupchat doesn't seem to include my own messages. It includes only messages of the other phone number in the groupchat. My messages to that said phone number are fine in normal chat but they are missing in any responses made in the groupchat (there's only two of us in the groupchat...), which isn't separated but is merged with the normal conversation. Any way to fix this? Thanks in advance.

**Comment by johanw666** [comment]
I think this is fixed in the 6.7.3.1-JW and later now the plaintext export had to be rewritten due to a database restructure. However, group information are not maintained in the export and groups are not used whith plaintext restore.
