### ISSUE TITLE
Will this fork support SMS after signal drops it?

### ISSUE THREAD

**Issue by Thal-J** [johanw666/Signal-Android#58]
Hi, coming here after signal announced that they would be dropping SMS support from the app (https://www.signal.org/blog/sms-removal-android/)

Will this fork continue this feature? I am interested in this fork at the least because of the apk expiry feature (so I can keep old version and keep SMS), but would also like to know if this is something that is feasible for the future of this fork.

There is currently a large thread about the removal of this feature on reddit (https://www.reddit.com/r/signal/comments/y27x4d/removing_sms_support_from_signal_android_soon/) and many people are thinking of an exodus from signal without this.

**Comment by johanw666** [comment]
No, I will not continue to support sms., doing so would require so much changes in Signal that it is way beyond the scope of this project.
