### ISSUE TITLE
Request to add amoled black as a theme

### ISSUE THREAD

**Issue by JohnBetaro** [johanw666/Signal-Android#65]
Hi,
I recently installed the app and i have to say thank you for all the hard work to make such a good fork with a lot of handy features.

Just asking if you can add a black theme for amoled screens because we're all waiting for this feature on the signal app.

Thank you for your time and effort.

**Comment by johanw666** [comment]
I had that in the past but I removd it because the frequent UI changes required too much time to maintain it.

**Comment by JohnBetaro** [comment]
I tried the signal fork called molly and it has the black theme is there any way to see their code and apply it on this fork ? Because I think it will help you maintain it .

And sorry if i'm wrong about anything I know you're trying your best already .

**Comment by johanw666** [comment]
Molly replaces the current dark theme with a black theme, that is much less work.

**Comment by JohnBetaro** [comment]
But I think it will be a good step forward if you do that because I think the majority of people prefer the black theme over the dark one

I hope you will rethink about it
