### ISSUE TITLE
Publish 2 variants of signal app if possible

### ISSUE THREAD

**Issue by JohnBetaro** [johanw666/Signal-Android#67]
Hi, I'm here again to talk about black theme in signal because you did not accept neither reject my pull request to replace the dark theme entirely with a black one, my guess is that you did not accept it.

So I'm here to ask you if there is any hope to publish 2 variants of the app, one with the normal dark and one with the black, I believe this will cost you so much less time than maintaining 2 themes in the same app, please consider my thoughts because i'm not the only one who is begging to have black theme.

I swear your app with the black theme and your additional features will be the perfect signal app ever existed, and thank you.

**Comment by soopstar** [comment]
I think that if people want this feature so badly, if @johanw666 is unwilling to add it in, and if it's just as simple as changing some colours in an xml file, someone should fork this fork and make the change. They've already stated that they're not doing this anymore due to frequent changes from Signal that break the AMOLED theme, if I remember correctly.

**Comment by JohnBetaro** [comment]
I think it's that easy if you just replace dark with black not adding the black with the dark in the same app, a good example is the signal fork called Molly, you can check their source code, and even @johanw666 said to me that it will be easy if he just replaces the dark with the black.

I just don't know how to make a fork, especially converting the source code into apk because I tried and had problems, I'm a nooby if just someone guides me through the process I will make my own fork for the people who want the black theme.

**Comment by soopstar** [comment]
Oh, I see what you mean. I just went and checked it out.
And don't worry, I don't know how to build an Android app, either, though, I'd like to think that I have a slight idea of how to make a fork.

**Comment by JohnBetaro** [comment]
So we're the same in this issue, I hope someone will help.

**Comment by Rebalance1092** [comment]
Come on guys you can do it.

**Comment by aravind-alpha07** [comment]
Hope he will consider🥲

**Comment by nekorubu** [comment]
[I think I did it.](https://github.com/nekorubu/Signal-Android/releases/tag/6.1.1.0-blackAlpha)

**Comment by JohnBetaro** [comment]
I'm going to try it and tell you

**Comment by JohnBetaro** [comment]
> [I think I did it.](https://github.com/nekorubu/Signal-Android/releases/tag/6.1.1.0-blackAlpha)

from what I can see there is no extra features that @johanw666 added in his fork, it's the original signal app with the black theme, I installed the universal version.

**Comment by JohnBetaro** [comment]
@nekorubu please give me something to contact you because i need your experience, i tried so many time to build the apk and failed, maybe you can help me to figure out what i'm doing wrong.

**Comment by aravind-alpha07** [comment]
![IMG_20221108_052048](https://user-images.githubusercontent.com/93417425/200440271-8482eef5-0e10-4617-8828-4643d6637481.jpg)
![Screenshot_2022-11-08-05-19-51-374_org thoughtcrime securesms](https://user-images.githubusercontent.com/93417425/200440320-fcb2486c-9334-4ef4-9e5c-a1212cb52244.png)

One of my friend helped me and made it.
Here is the [download link for 6.1.1.0-JW](https://mega.nz/file/TvpBzQqa#ARGm9hoVYIcwSAOVa99dmncj6_1wxwm8aHpUxioiLbU)  (arm64v8a) with amoled black theme.

**Comment by nekorubu** [comment]
> > [I think I did it.](https://github.com/nekorubu/Signal-Android/releases/tag/6.1.1.0-blackAlpha)
> 
> from what I can see there is no extra features that @johanw666 added in his fork, it's the original signal app with the black theme, I installed the universal version.

Oh, now I see what you mean, and I think I know why that happened: I only forked over the main branch and none of the others

**Comment by JohnBetaro** [comment]
> ![IMG_20221108_052048](https://user-images.githubusercontent.com/93417425/200440271-8482eef5-0e10-4617-8828-4643d6637481.jpg)
> ![Screenshot_2022-11-08-05-19-51-374_org thoughtcrime securesms](https://user-images.githubusercontent.com/93417425/200440320-fcb2486c-9334-4ef4-9e5c-a1212cb52244.png)
> 
> One of my friend helped me and made it.
> Here is the [download link for 6.1.1.0-JW](https://mega.nz/file/TvpBzQqa#ARGm9hoVYIcwSAOVa99dmncj6_1wxwm8aHpUxioiLbU)  (arm64v8a) with amoled black theme.
>  
> 

It will be better if he published the app on github with the source code.

**Comment by JohnBetaro** [comment]
> > > [I think I did it.](https://github.com/nekorubu/Signal-Android/releases/tag/6.1.1.0-blackAlpha)
> > 
> > from what I can see there is no extra features that @johanw666 added in his fork, it's the original signal app with the black theme, I installed the universal version.
> 
> Oh, now I see what you mean, and I think I know why that happened: I only forked over the main branch and none of the others

So is there any way to fix the issue ?

**Comment by aravind-alpha07** [comment]
> .

He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked

**Comment by JohnBetaro** [comment]
> > .
> 
> He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> 

Is it hard to do ? maybe if it is easy we can do it every time we need an update ?
Can your friend at least make a little tutorial on how to do this please.

**Comment by aravind-alpha07** [comment]
> > > .
> > 
> > 
> > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> 
> Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.

Sure I'll ask him & let you know
Btw do you face any issues after restoring backups? 
Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key

Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
This very annoying everytime

**Comment by JohnBetaro** [comment]
> > > > .
> > > 
> > > 
> > > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> > 
> > Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.
> 
> Sure I'll ask him & let you know
> Btw do you face any issues after restoring backups? 
> Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key
> 
> Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
> This very annoying everytime

No, I think every thing is fine, by the way I managed to unpack the apk and get access to the .xml files, all i need is to ask your friend which files I should be looking at and I'll do the rest, because the names are different from the github's source code, thank you in advance

**Comment by aravind-alpha07** [comment]
> > > > > .
> > > > 
> > > > 
> > > > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> > > 
> > > Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.
> > 
> > Sure I'll ask him & let you know
> > Btw do you face any issues after restoring backups? 
> > Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key
> > 
> > Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
> > This very annoying everytime
> 
> No, I think every thing is fine, by the way I managed to unpack the apk and get access to the .xml files, all i need is to ask your friend which files I should be looking at and I'll do the rest, because the names are different from the github's source code, thank you in advance

Tools needed: [MT MANAGER](https://t.me/mtmanager)  

STEPS : Unpack Apk & open resources.arsc with arsc editor then locate to the following path and edit HEX values

org.thoughtcrime.securesms/color/color-night/signal_colorBackground FF000000

(ID: 7F06043F)

org.thoughtcrime.securesms/color/color-night/signal_dark_colorSurface2
FF000000

(ID: 7F060489)

Or you can search both by HEX values and replace by those mentioned values (if you can't find the path you can also search by ID using mentioned above & and then save the changes repack and install good to go.

I'm thinking of releasing upcoming every updates in future (AMOLED BLACK). Incase you are lazy to do, you can dwld from my fork.Thank you

**Comment by JohnBetaro** [comment]
I know you already gave me to much but I just need one last step which is how to build the apk again after the edit.

**Comment by JohnBetaro** [comment]
> > > > > > .
> > > > > 
> > > > > 
> > > > > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> > > > 
> > > > Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.
> > > 
> > > Sure I'll ask him & let you know
> > > Btw do you face any issues after restoring backups? 
> > > Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key
> > > 
> > > Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
> > > This very annoying everytime
> > 
> > No, I think every thing is fine, by the way I managed to unpack the apk and get access to the .xml files, all i need is to ask your friend which files I should be looking at and I'll do the rest, because the names are different from the github's source code, thank you in advance
> 
> Tools needed: [MT MANAGER](https://t.me/mtmanager)  
> 
> STEPS : Unpack Apk & open resources.arsc with arsc editor then locate to the following path and edit HEX values
> 
> org.thoughtcrime.securesms/color/color-night/signal_colorBackground FF000000
> 
> (ID: 7F06043F)
> 
> org.thoughtcrime.securesms/color/color-night/signal_dark_colorSurface2
> FF000000
> 
> (ID: 7F060489)
> 
> Or you can search both by HEX values and replace by those mentioned values (if you can't find the path you can also search by ID using mentioned above & and then save the changes repack and install good to go.
> 
> I'm thinking of releasing upcoming every updates in future (AMOLED BLACK). Incase you are lazy to do, you can dwld from my fork.Thank you 

I know you already gave me to much but I just need one last step which is how to build the apk again after the edit.

**Comment by aravind-alpha07** [comment]
> > > > > > > .
> > > > > > 
> > > > > > 
> > > > > > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> > > > > 
> > > > > Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.
> > > > 
> > > > Sure I'll ask him & let you know
> > > > Btw do you face any issues after restoring backups? 
> > > > Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key
> > > > 
> > > > Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
> > > > This very annoying everytime
> > > 
> > > No, I think every thing is fine, by the way I managed to unpack the apk and get access to the .xml files, all i need is to ask your friend which files I should be looking at and I'll do the rest, because the names are different from the github's source code, thank you in advance
> > 
> > Tools needed: [MT MANAGER](https://t.me/mtmanager)  
> > 
> > STEPS : Unpack Apk & open resources.arsc with arsc editor then locate to the following path and edit HEX values
> > 
> > org.thoughtcrime.securesms/color/color-night/signal_colorBackground FF000000
> > 
> > (ID: 7F06043F)
> > 
> > org.thoughtcrime.securesms/color/color-night/signal_dark_colorSurface2
> > FF000000
> > 
> > (ID: 7F060489)
> > 
> > Or you can search both by HEX values and replace by those mentioned values (if you can't find the path you can also search by ID using mentioned above & and then save the changes repack and install good to go.
> > 
> > I'm thinking of releasing upcoming every updates in future (AMOLED BLACK). Incase you are lazy to do, you can dwld from my fork.Thank you 
> 
> I know you already gave me to much but I just need one last step which is how to build the apk again after the edit.

![Screenshot_2022-11-08-13-16-47-987_bin.mt.plus.png](https://user-images.githubusercontent.com/93417425/200504465-43463d4e-af02-4c39-9a9c-3017c9ece5ac.png) better do this way coz its very handy click on apk & select the view option and edit the contents then it will ask for save or discard after making changes click save that's all contents will be edited

**Comment by JohnBetaro** [comment]
> > > > > > > > .
> > > > > > > 
> > > > > > > 
> > > > > > > He didn't built the apk from source.. extracted the apk & made changes on UI hex color then repacked
> > > > > > 
> > > > > > Is it hard to do ? maybe if it is easy we can do it every time we need an update ? Can your friend at least make a little tutorial on how to do this please.
> > > > > 
> > > > > Sure I'll ask him & let you know
> > > > > Btw do you face any issues after restoring backups? 
> > > > > Whenever after i restored my backup the recovery key for the old backup remains same and after giving storage permission for the app the old recovery key got deleted in settings and asks to create a new backup with new recovery key
> > > > > 
> > > > > Whenever i changes my devices or reinstalling the app i have to create new recovery key & backup 
> > > > > This very annoying everytime
> > > > 
> > > > No, I think every thing is fine, by the way I managed to unpack the apk and get access to the .xml files, all i need is to ask your friend which files I should be looking at and I'll do the rest, because the names are different from the github's source code, thank you in advance
> > > 
> > > Tools needed: [MT MANAGER](https://t.me/mtmanager)  
> > > 
> > > STEPS : Unpack Apk & open resources.arsc with arsc editor then locate to the following path and edit HEX values
> > > 
> > > org.thoughtcrime.securesms/color/color-night/signal_colorBackground FF000000
> > > 
> > > (ID: 7F06043F)
> > > 
> > > org.thoughtcrime.securesms/color/color-night/signal_dark_colorSurface2
> > > FF000000
> > > 
> > > (ID: 7F060489)
> > > 
> > > Or you can search both by HEX values and replace by those mentioned values (if you can't find the path you can also search by ID using mentioned above & and then save the changes repack and install good to go.
> > > 
> > > I'm thinking of releasing upcoming every updates in future (AMOLED BLACK). Incase you are lazy to do, you can dwld from my fork.Thank you 
> > 
> > I know you already gave me to much but I just need one last step which is how to build the apk again after the edit.
> 
> ![Screenshot_2022-11-08-13-16-47-987_bin.mt.plus.png](https://user-images.githubusercontent.com/93417425/200504465-43463d4e-af02-4c39-9a9c-3017c9ece5ac.png) better do this way coz its very handy click on apk & select the view option and edit the contents then it will ask for save or discard after making changes click save that's all contents will be edited. I did this way.

I don't know how to thank you my brother, you really helped me to solve the problems. Thank you a lot.

**Comment by JohnBetaro** [comment]
[I did it too](https://github.com/JohnBetaro/Signal-Android-AMOLED-Black)

**Comment by aravind-alpha07** [comment]
> [I did it too](https://github.com/JohnBetaro/Signal-Android-AMOLED-Black)

Nice post it in reddit & 
Do we get regular updates?

**Comment by JohnBetaro** [comment]
> > [I did it too](https://github.com/JohnBetaro/Signal-Android-AMOLED-Black)
> 
> Nice post it in reddit & 
> Do we get regular updates? 
> 

I said in the description I'll try my best to do frequent updates (at least once a month) because I use the app everyday

**Comment by JohnBetaro** [comment]
is there anyone here using my app ? just asking
