### ISSUE TITLE
Unable to restore encrypted backup from most recent version of Signal.

### ISSUE THREAD

**Issue by daedesign** [johanw666/Signal-Android#7]
### Bug description
Unable to restore encrypted backup from most recent version of Signal.

I exported a .BACKUP file from my original Signal app.
Then I deleted the app and installed your APK.
I place the .BACKUP file in the /signal, /signal/Backups, and /signal/FullBackups
When I hit "Restore encrypted backup" & "Restore" I received the "No encrypted Backup found!" error. 

My whole goal is to convert my encrypted .BACKUP into a XML/CSV in order to migrate it to another messaging app. Any help would be overwhelmingly appreciated. 

### Device info

**Device:** OnePlus 5T
**Android version:** 9.0.11
**Signal version:** 4.58.5.1-JW

**Comment by johanw666** [comment]
The backup from the officiel client should be in Backups. I've just tested this and it works with 4.58.5.1-JW, can you provide a logfile?

**Comment by Go-rom** [comment]
Hello,

i did the same thing friday and it worked.

But you have to know that a backup made with the original Signal app has to be restored at the first start of Signal (Johan's fork)
You used the import/export menu but it's not meant to be used for backup from original Signal, only for backups made with Johan's import/export tool.

**Comment by speed47** [comment]
Thanks @go-rom for your remark, I swapped from the original Signal app to the johanw666's fork today, and was confused that the import menu didn't ask me to locate my original Signal backup file.
Maybe it's just something to add in the menu, that this "type" of backup is only the johanw666's fork backup, and that the original backup must be restored at the first application launch & will be *silently* skipped if no backup is found in the expected location.

**Comment by johanw666** [comment]
If you are not on an initial setup you can select the backup location in the Settings - Chats and media menu in Backups - Backup location. This location will then be used for all backups, the ones from my extra menu and the official backups that can be used when you freshlyy setup Signal.

If you are freshly setting up Signal my frk will look for a backup in the internal memory first, if it can't find it there it will look on the removable storage (and when it isn't there as well it will not offer a restore).

if you want to restore an encrypted backup made with my export tool on a fresh install there is no other way than to register Signal first, then import the backup. I have plans to add this functionality but I need to find the time
