### ISSUE TITLE
Unable to create chat backups

### ISSUE THREAD

**Issue by panomitrius** [johanw666/Signal-Android#71]
### Bug description
Unable to create backups.

### Steps to reproduce
- Open Signal app
- Go to Chat backups
- Click Create backup (says "Last backup: unknown")

**Actual result:** [Nothing happens]
**Expected result:** Backup would be created

### Screenshots
![signal-2022-11-22-184251](https://user-images.githubusercontent.com/75156060/203384348-edbe2678-ff37-47c5-83e0-45488ebdb7ab.png)

### Device info

**Device:** Samsung S10E
**Android version:** lineage_beyond0lte-userdebug 12 SQ3A.220705.004 eng.root.20221017.193918 dev-keys
**Signal version:** 6.3.2.0-JW

### Link to debug log

https://debuglogs.org/android/6.3.2/64d6a9c3e18d939dcefa93843a2e74a16c86a137ae11469048d60b3cc944152c

**Comment by panomitrius** [comment]
Seems to be solved by giving Signal permission to all files. But didn't work with the regular permission given from the pop-up that showed up when I chose the backup folder.

**Comment by johanw666** [comment]
No, that is a different permission. But it should ask for the file management permission if it does not have it and you try to create a backup in the import/export screen.
