### ISSUE TITLE
SMS support

### ISSUE THREAD

**Issue by Teetoow** [johanw666/Signal-Android#76]
Hi, 

Since official signal app removed the SMS support, is it possible for your fork to keep getting sms working? I tried this app thinking sms was still available but i didn't found how to enable it.
Thanks in advance.

**Comment by robjob1938** [comment]
Teetoow, the apk expire is turned off on this apk.  You can download the older Jan 13 version before the SMS timer was installed.  

https://github.com/johanw666/Signal-Android/releases/tag/v6.8.2.0-JW

It would be better if the developer disabled the SMS timer on a newer version, but I doubt they will.  Please note, backups don't work when going to an older version, so you will start from scratch.
