### ISSUE TITLE
Whatsapp Messages Import fails

### ISSUE THREAD

**Issue by blaugrau3001** [johanw666/Signal-Android#86]
When I try to import the msgstore.db it just gives me _Error importing Backup_
The file is correct because other programs like WhatsApp Viewer can read the file, idk really know what could be the reason for the error, I am not so good in Android programming so I have just the logs, maybe someone who is better than me can help.

> `09-08 23:58:47.650 21111 21198 W PlaintextBackupImporter: importWhatsapp(): importGroup: true, avoidDuplicates: true
> 09-08 23:58:47.651 21111 21198 W DEBUG_CONTEXT: getDatabasePath(msgstore.db) = /storage/emulated/0/msgstore.db
> 09-08 23:58:47.652 21111 21151 D OpenGLRenderer: endAllActiveAnimators on 0x7594b06670 (RippleDrawable) with handle 0x74a4742ac0
> 09-08 23:58:47.662 21111 21198 W WhatsappBackup: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
> 09-08 23:58:47.663 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.663 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.663 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.663 21111 21198 W ServiceId:
> 09-08 23:58:47.666 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.666 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.666 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.666 21111 21198 W ServiceId:
> 09-08 23:58:47.672 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.672 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.672 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.672 21111 21198 W ServiceId:
> 09-08 23:58:47.674 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.674 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.674 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.674 21111 21198 W ServiceId:
> 09-08 23:58:47.679 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.679 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.679 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.679 21111 21198 W ServiceId:
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase: Error inserting
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase: android.database.sqlite.SQLiteConstraintException: FullCode: 1299 | ErrorCode: 19 | ExtendedErrorCode: 5 | Message: NOT NULL constraint failed: message.to_recipient_id | ExtraMessage: null
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecuteForLastInsertedRowId(Native Method)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteConnection.executeForLastInsertedRowId(SQLiteConnection.java:818)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteSession.executeForLastInsertedRowId(SQLiteSession.java:823)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteStatement.executeInsert(SQLiteStatement.java:114)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteDatabase.insertWithOnConflict(SQLiteDatabase.java:1766)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at net.zetetic.database.sqlcipher.SQLiteDatabase.insert(SQLiteDatabase.java:1635)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.SQLiteDatabase.lambda$insert$9(SQLiteDatabase.java:370)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.SQLiteDatabase.$r8$lambda$eBR4RIjrRyyBXYMF_BA_zlT3YmA(SQLiteDatabase.java:0)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.SQLiteDatabase$$ExternalSyntheticLambda10.run(R8$$SyntheticClass:0)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.SQLiteDatabase.traceSql(SQLiteDatabase.java:112)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.SQLiteDatabase.insert(SQLiteDatabase.java:370)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.WhatsappBackupImporter.insertMms(WhatsappBackupImporter.java:206)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:91)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.684 21111 21198 E SQLiteDatabase:        at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.684 21111 21198 D AttachmentTable: insertParts(1)
> 09-08 23:58:47.684 21111 21198 D AttachmentTable: Inserting attachment for mms id: -1
> 09-08 23:58:47.687 21111 21198 D AttachmentTable: Wrote part to file: /data/user/0/org.thoughtcrime.securesms/app_parts/part3815737017294121951.mms
> 09-08 23:58:47.687 21111 21198 I AttachmentTable: [deduplicateAttachment] No acceptable matching attachment data found. /data/user/0/org.thoughtcrime.securesms/app_parts/part3815737017294121951.mms
> 09-08 23:58:47.696 21111 21198 I AttachmentTable: Inserted attachment at ID: AttachmentId::(1671, 1694210327684)
> 09-08 23:58:47.697 21111 21198 W ServiceId: [parseOrNull(String)] Invalid ServiceId!
> 09-08 23:58:47.697 21111 21198 W ServiceId: org.signal.libsignal.protocol.ServiceId$InvalidServiceIdException
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.signal.libsignal.protocol.ServiceId.parseFromString(ServiceId.java:87)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId$Companion.parseOrNull(ServiceId.kt:44)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.whispersystems.signalservice.api.push.ServiceId.parseOrNull(ServiceId.kt:0)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.recipients.Recipient.external(Recipient.java:343)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.getRecipient(WhatsappBackupImporter.java:156)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:81)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.697 21111 21198 W ServiceId:     at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.697 21111 21198 W ServiceId:
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter: null
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter: android.database.sqlite.SQLiteConstraintException: FullCode: 1299 | ErrorCode: 19 | ExtendedErrorCode: 5 | Message: NOT NULL constraint failed: message.to_recipient_id | ExtraMessage: null
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at net.zetetic.database.sqlcipher.SQLiteConnection.nativeExecute(Native Method)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at net.zetetic.database.sqlcipher.SQLiteConnection.execute(SQLiteConnection.java:591)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at net.zetetic.database.sqlcipher.SQLiteSession.execute(SQLiteSession.java:623)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at net.zetetic.database.sqlcipher.SQLiteStatement.execute(SQLiteStatement.java:51)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at org.thoughtcrime.securesms.database.WhatsappBackupImporter.insertSms(WhatsappBackupImporter.java:226)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:95)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.700 21111 21198 W PlaintextBackupImporter:       at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment: null
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment: java.io.IOException: Whatsapp Import error!
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at org.thoughtcrime.securesms.database.WhatsappBackupImporter.importWhatsappFromSd(WhatsappBackupImporter.java:108)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:180)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at org.thoughtcrime.securesms.ImportExportFragment$ImportWhatsappBackupTask.doInBackground(ImportExportFragment.java:125)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at android.os.AsyncTask$3.call(AsyncTask.java:394)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
> 09-08 23:58:47.702 21111 21198 W ImportExportFragment:  at java.lang.Thread.run(Thread.java:920)
> 09-08 23:58:47.750 21111 21111 E MainContentCaptureSession: handleForceFlush(act:org.thoughtcrime.securesms/.ImportExportActivity [state=2 (ACTIVE), disabled=true], reason=VIEW_ROOT): should not be when disabled
> 09-08 23:58:48.647 21111 21184 D MemoryTracker: Used memory has increased or stayed the same for the last 55 intervals (275 seconds). Using: 70033800 (66.79 MiB), Free: 8632024 (8.23 MiB), CurrentTotal: 78665824 (75.02 MiB), MaxPossible: 536870912 (512.00 MiB)
> 09-08 23:59:13.837 21111 21184 D MemoryTracker: Used memory has increased or stayed the same for the last 60 intervals (300 seconds). Using: 70548832 (67.28 MiB), Free: 8116992 (7.74 MiB), CurrentTotal: 78665824 (75.02 MiB), MaxPossible: 536870912 (512.00 MiB)`

I have Version 6.32.1.0-JW installed on Android 12

**Comment by johanw666** [comment]
I'm not surprised, this functionalty is at the moment outdated and not maintained. The original maintainers wanted me to include it but didn't want to maintain it and I have at the moment no time to maintain it. So it will have to wait until I have more time.
