### ISSUE TITLE
Molly-like multi device support?

### ISSUE THREAD

**Issue by alexaka1** [johanw666/Signal-Android#87]
This got merged not long ago into Molly  [PR](https://github.com/mollyim/mollyim-android/pull/157).

Are there any plans to integrate something similar? Molly allows linking a fresh install as a device without registering.

**Comment by johanw666** [comment]
This requires quite a lot of changes, I don't have time now to maintain this functionality.

**Comment by alexaka1** [comment]
Would #83 be something similar? Not linking a device directly, but simply restoring a backup without re-registering.

**Comment by johanw666** [comment]
It is something I intend to do eventually. However it can ony be done with a full backup, not with a Signal style backup because that misses information like gms tokens.
