### ISSUE TITLE
[Feature Request] Live Location sharing

### ISSUE THREAD

**Issue by blaugrau3001** [johanw666/Signal-Android#88]
I know that feature request have to be made in the signal forum, but this feature was requested a lot of times but none really cared. Maybe you think that this is a good feature, after the edit message feature added, you may have the ability to edit a message to make it update the GPS coordinates.
This would be a very cool feature to implement.

**Comment by johanw666** [comment]
Sorry but this is not something I'm going to implement. I never use it myself on apps that do support it.
