### ISSUE TITLE
Feature Request: Remove mandatory PIN creation on first launch

### ISSUE THREAD

**Issue by derMart** [johanw666/Signal-Android#9]
Sadly the Signal folks are very stubborn about the mandatory online storage.
Also on this fork yet we have to create a PIN and as such expose private data unsecurely to the signal servers.
Do you think it is possible and feasible to remove this on first launch?

**Comment by johanw666** [comment]
Not without redesigning a lot of stuff, which is
- too maintenace heavy for this project,
- it remains to be seen wether that will be possible with future server releases

In the mean time I suggest using a long alphanumeric pin to protect your data.

**Comment by derMart** [comment]
Hey, I've had a look at the code and at least currently, it seems very little is needed to disable the forced creation of PINs. Have a look at #10 :-)
For me, this worked in the following scenario: Have device A with Signal without PIN setup and moved to device B importing the backup of device A. Probably it will also work for new registrations.

**Comment by KarmusDK** [comment]
If you want to avoid the dialog box nagging and blocking access to your inbox, just leave an SMS message unread. (Doesn't work anymore if you swap SIM cards.)
