### ISSUE TITLE
Reconsider adding SMS/MMS support to this fork

### ISSUE THREAD

**Issue by WSLUser** [johanw666/Signal-Android#92]
### Bug description
Describe here the issue that you are experiencing.

I was using Jerry's fork from here for SMS support but it seems my version of Signal is too old as the Signal server is no longer letting me send or receive Signal messages but I used this app for SMS and MMS as well and still need that functionality.  It appears Jerry abandoned his fork of this fork so I'm requesting this be properly added back here in this fork.

I believe this fork could keep this functionality the same way plain text backups are maintained as that was another feature Signal officially removed. Or if different,  simply revert all the commits causing both the removal and warnings of pending removal. I do not think there should be much changes after that to ensure it works. I'd do this myself but I'm no expert in git or coding.

### Device info

Device: Samsung Galaxy S10
**Android version:** 12.0
**Signal version:** 6.26.2.0-JW-JK

**Comment by johanw666** [comment]
This is way too much work and especially maintenance for a function I don't use anyway, after Signal dropped sms encryption I use the Signal fork Silence, aimed at sms, for that.

**Comment by WSLUser** [comment]
Link?

**Comment by johanw666** [comment]
https://silence.im/ , source code on https://github.com/SilenceIM/Silence
