### ISSUE TITLE
New usernames all "taken"

### ISSUE THREAD

**Issue by Terrance** [johanw666/Signal-Android#93]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] I have read https://github.com/signalapp/Signal-Android/wiki/Submitting-useful-bug-reports
- [x] This isn't a feature request or a discussion topic

----------------------------------------

### Bug description

7.0.0 seems to include the new username feature that's been in testing, though it's currently reporting "This username is taken." for any username I give it.  Logcat reports similarly:

```
D RefreshOwnProfileJob: Local and remote username hash are both empty. Considering validated.
I AccountValues: Marking username sync state as: IN_SYNC
...
W UsernameRepository: [reserveUsername] Username taken.
```

Without having a stock client to hand, I'm not sure if this has actually been launched yet and just isn't working in this fork, or isn't actually available on Signal's servers yet (there doesn't seem to be an upstream 7.0.0 release yet).

### Steps to reproduce

- Settings > Profile > Username
- try assigning yourself one

### Device info

**Device:** OnePlus Nord CE
**Android version:** 13
**Signal version:** 7.0.0.0-JW

**Comment by johanw666** [comment]
This is a server-side isssue, when the server switches on usernames they can be setup.

**Comment by Terrance** [comment]
Just to confirm, usernames are now live and this seems to be working as expected. 👍
