### ISSUE TITLE
Amoled Black dark mode

### ISSUE THREAD

**Issue by QBANIN** [johanw666/Signal-Android#96]
Hi! Any chance to add Amoled Black dark mode like in Molly?

**Comment by nekorubu** [comment]
It's likely gonna be a no from @johanw666. There was a fork that gave you this feature, but the person maintaining it seems to be gone.

**Comment by QBANIN** [comment]
> (...) There was a fork that gave you this feature, but the person maintaining it seems to be gone.

I know that. I'm using latest build of that fork but for some reason whole repo is gone (404 /deleted??)

**Comment by nekorubu** [comment]
Oh, I'm sorry. That explains why you're here. I didn't even know the repo was gone until I went rooking for it to reference.

**Comment by aravind-alpha07** [comment]
> > (...) There was a fork that gave you this feature, but the person maintaining it seems to be gone.
> 
> I know that. I'm using latest build of that fork but for some reason whole repo is gone (404 /deleted??)

John Betaro right? Yeah I'm searching for his fork couldn't find.. seems he deleted his account.

**Comment by johanw666** [comment]
As have said before, I won't make any changes to the themes. Because of the extremely high change rate that gives too much maintenance work.

**Comment by The-Kyber** [comment]
https://github.com/The-Kyber/Signal-AMOLED

a fork that I will be maintaining in my free time

**Comment by QBANIN** [comment]
Well, I already forked and modified it myself :)

**Comment by The-Kyber** [comment]
two forks are better than one I guess, mine is automated locally on my machine, maybe I will use GitHub Actions in the future

**Comment by aravind-alpha07** [comment]
> Well, I already forked and modified it myself :)

Can you share yours?

**Comment by QBANIN** [comment]
> > Well, I already forked and modified it myself :)
> 
> Can you share yours?

https://github.com/QBANIN/Signal-Android

**Comment by aravind-alpha07** [comment]
> > > Well, I already forked and modified it myself :)
> > 
> > 
> > Can you share yours?
> 
> https://github.com/QBANIN/Signal-Android

Thank you
