### ISSUE TITLE
ClassNotFoundException: org.signal.libsignal.net.NetworkException

### ISSUE THREAD

**Issue by Terrance** [johanw666/Signal-Android#98]
As of 7.4.0.0-JW, Signal is repeatedly crashing with the following:

```
FATAL EXCEPTION: Thread-10
Process: org.thoughtcrime.securesms, PID: 3480
java.lang.ClassNotFoundException: org.signal.libsignal.net.NetworkException
```

**Comment by johanw666** [comment]
I have no idea how that is caused, on my device it works OK. Cab you send a debug log? Without it I can't see what happens.

**Comment by johanw666** [comment]
Yes, and at least the app should not crash. However, this seems a Signal issue not specifically tied to this fork. One of us could open an issue in the Signal repo because they will have to fix this.

**Comment by johanw666** [comment]
I think https://github.com/signalapp/Signal-Android/commit/b3336b4d84def3c167b5fd115d1b5395cb06c65f might have fixed this.

**Comment by Terrance** [comment]
Yep, picked up the update here yesterday and connection failures seem to be handled properly now (looks like that request goes out once a day, so I had to wait a bit for it to trigger again).
