### ISSUE TITLE
The app does not use GMS for notifications.

### ISSUE THREAD

**Issue by TheKyber** [johanw666/Signal-Android#99]
It thinks that the device does not support Google Play Services but it is installed and all other apps are working just fine.

I don't know if the problem is only in the latest version "7.4.0" because I have not been using Google Play Services before it.

I tried it on a GrapheneOS device with sandboxed Google Play Services many times. (Pixel 7a with Android 14)

And I also tried on a Pixel running the Stock Android (Pixel 4XL with Android 13)

I hope you will take a look at it, I don't know if the problem is only in your fork or is it from upstream.

This photo is from a Pixel running the Stock Android.

<details>
<summary> Screenshot </summary> <br>

![signal-2024-04-12-12-03-59-995](https://github.com/johanw666/Signal-Android/assets/166752829/503aa90a-f532-46d9-a392-f7e57874d932)

</details>

Logs:

[Signal log ec345da3974f.txt](https://github.com/johanw666/Signal-Android/files/14961295/Signal.log.ec345da3974f.txt)

**Comment by TheKyber** [comment]
I am here to say that I tried many older releases of your fork that go back to February and even December and they have the same problem (but back then they were working just fine).

I tried the official app from Signal's website (7.2.4) and it worked normally.

The tests were performed on the Stock Android (Pixel 4XL).

**Comment by TheKyber** [comment]
Update:
I compiled the app from the source code of Signal's official GitHub repo and I am facing the same problem (7.4.1).

**Comment by TheKyber** [comment]
I managed to solve the issue. Someone had the same one as mine.
https://github.com/signalapp/Signal-Android/issues/13451

I hope I will get an answer from you on why your app also did not work, is it because you also did not change the values?

**Comment by johanw666** [comment]
I didn't change anything there. I did add an option to switch between fcm and websockets but that does not change anything in the fcm code.

**Comment by Go-rom** [comment]
Hello @johanw666 

I've just encountered the same issue with a Galaxy S22+ (not rooted) completely reset and Signal 7.6.2.1-JW (i didn't find the last stable release 7.7.2)
Then i tried the official version (last release on G Play : 7.7.2) and it works fine.

If you're interested to investigate more, i'll run a new try with the next stable 7.8.x and provide debug logs.
